server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jun.vxin.domain
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vxin?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 5000
      auto-commit: true
      maximum-pool-size: 16
      minimum-idle: 4
      idle-timeout: 60000
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: ****************************
      keysecret: ******************************
      bucketname: vxin
